# Generated by Django 4.2.10 on 2025-06-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
