# Generated by Django 4.2.10 on 2025-06-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_number_alter_order_status_and_more'),
    ]

    operations = [
    ]
